[package]
name = "op-challenger"
description = "Binary crate for the op-challenger"
authors = ["clabby"]
version = "0.1.0"
edition = "2021"

[dependencies]
# External
clap = { version = "4.1.13", features = ["derive", "env"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
anyhow = "1.0.70"
ethers = "2.0.2"
tokio = { version = "1.27.0", features = ["macros"] }

# Local
op-challenger-driver = { path = "../crates/driver" }
op-challenger-tui = { path = "../crates/tui" }

[[bin]]
name = "op-challenger"
path = "src/op-challenger.rs"
